# Generated by Django 4.0.5 on 2022-06-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usermessage_delete_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='subject',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
